name: Build and Deploy to Docker Hub

env:
  BASE_IMAGE: nginx:stable-alpine
  IMAGE_NAME: nginx-letsencrypt

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit hash
        id: commit_hash
        run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest base image
        run: docker pull ${{ env.BASE_IMAGE }}

      - name: Extract Nginx version
        id: nginx_version
        run: |
          NGINX_VERSION=$(docker inspect ${{ env.BASE_IMAGE }} | grep NGINX_VERSION | awk -F '=' '{print $2}' | tr -d '",')
          echo "nginx_version=$NGINX_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.nginx_version }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.nginx_version }}-${{ env.commit }}

