name: Rebuild and Deploy if Base Image Updates

env:
  BASE_IMAGE: nginx:stable-alpine
  IMAGE_NAME: nginx-letsencrypt

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull latest base image
        run: docker pull ${{ env.BASE_IMAGE }}

      - name: Check if base image is updated
        id: image_updated
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.BASE_IMAGE }})
          if [ "$DIGEST" != "$(cat digest.txt 2>/dev/null)" ]; then
            echo "$DIGEST" > digest.txt
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract Nginx version
        if: steps.image_updated.outputs.updated == 'true'
        id: nginx_version
        run: |
          FULL_VERSION=$(docker inspect ${{ env.BASE_IMAGE }} | grep NGINX_VERSION | awk -F '=' '{print $2}' | tr -d '",')
          MAJOR_MINOR=$(echo "$FULL_VERSION" | awk -F '.' '{print $1"."$2}')
          echo "full_version=$FULL_VERSION" >> $GITHUB_ENV
          echo "minor_version=$MAJOR_MINOR" >> $GITHUB_ENV
          
      - name: Checkout repository
        if: steps.image_updated.outputs.updated == 'true'
        uses: actions/checkout@v4

      - name: Get commit hash
        if: steps.image_updated.outputs.updated == 'true'
        id: commit_hash
        run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: steps.image_updated.outputs.updated == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.image_updated.outputs.updated == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.minor_version }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.full_version }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.full_version }}-${{ env.commit }}

